<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Scratch prefix
    |--------------------------------------------------------------------------
    |
    | Names generated by `splicewire:beam:dev:isolated-test-db` start with this, and
    | `drop-db` refuses to drop anything that doesn't (without --force). It is the
    | line between "a throwaway this tool made" and "someone's database that happens
    | to live on the same server", so keep it distinctive.
    |
    */
    'prefix' => env('BEAM_DEV_DB_PREFIX', 'test_'),

    /*
    |--------------------------------------------------------------------------
    | Env vars that must point at the scratch database
    |--------------------------------------------------------------------------
    |
    | Every variable listed here is emitted by `isolated-test-db`, all set to the new
    | database. List ALL of them, not just the obvious one.
    |
    | This is the step projects get half-right. It is common for the test connection to
    | read one variable while other connections on the same server read another — so
    | overriding only the first leaves part of the app still talking to the shared
    | database, and the isolation silently does nothing. If a project has a second
    | connection (a `central` alongside a tenant one, a reporting replica, a queue
    | database), name its variable here too.
    |
    | You do not have to get this right for isolation to work. `isolated-test-db` also READS
    | the project's test harness (tests/*.php, phpunit.xml, testbench.yaml, .env.testing) for
    | any `env('*DB_DATABASE')` it selects its database with, and emits the union of the two
    | lists — saying out loud which files it read them from. This list is how you stop
    | rediscovering; it is not what makes the tool correct.
    |
    */
    'env' => ['DB_DATABASE'],

    /*
    |--------------------------------------------------------------------------
    | Where the harness scan looks
    |--------------------------------------------------------------------------
    |
    | Null means the sensible pair: the working directory and the application base path.
    | Both, because under `vendor/bin/testbench` the base path is the testbench SKELETON in
    | vendor/ and the harness worth reading is in the repo you are standing in.
    |
    | An EMPTY array disables discovery entirely, and then `config('beam.dev.env')` above is
    | the only source of env var names. That is a deliberate choice with a cost: it is the
    | configuration under which this tool once printed a variable no suite read.
    |
    */
    'harness_paths' => null,

    /*
    |--------------------------------------------------------------------------
    | Where SQLite scratch files live
    |--------------------------------------------------------------------------
    |
    | Null means a project-scoped directory under the system temp dir. Deliberately NOT
    | beside the connection's own database file: scratch this tool creates must never turn
    | up in a consumer's `git status`, and the old `dirname($configured)` rule resolved to
    | the process's working directory whenever the connection was `:memory:` — which is how
    | a stray `test_<slug>.sqlite` ended up committed-adjacent in a package repo root.
    |
    | The directory is stable rather than pid-keyed on purpose: the drop runs in a different
    | process than the create and has to be able to find the file. The SESSION key is the
    | file NAME (`test_<random>`), which is what actually keeps two runs apart.
    |
    */
    'sqlite_dir' => env('BEAM_DEV_SQLITE_DIR'),

    /*
    |--------------------------------------------------------------------------
    | Provisioning SQL
    |--------------------------------------------------------------------------
    |
    | SQL files run INSIDE a freshly created database, before anything migrates.
    | Paths are relative to the project root unless absolute.
    |
    | This is for what a schema assumes already exists: Postgres extensions, roles,
    | a search_path. Without it the failure is quiet and misleading — the database is
    | created fine, and then the first migration needing `citext` or `vector` fails
    | with an error about the extension rather than about the missing setup step.
    |
    |   'init' => ['database/init/extensions.sql'],
    |
    */
    'init' => [],

];
