<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Scratch prefix
    |--------------------------------------------------------------------------
    |
    | Names generated by `splicewire:beam:dev:isolated-test-db` start with this, and
    | `drop-db` refuses to drop anything that doesn't (without --force). It is the
    | line between "a throwaway this tool made" and "someone's database that happens
    | to live on the same server", so keep it distinctive.
    |
    */
    'prefix' => env('BEAM_DEV_DB_PREFIX', 'test_'),

    /*
    |--------------------------------------------------------------------------
    | Env vars that must point at the scratch database
    |--------------------------------------------------------------------------
    |
    | Every variable listed here is emitted by `isolated-test-db`, all set to the new
    | database. List ALL of them, not just the obvious one.
    |
    | This is the step projects get half-right. It is common for the test connection to
    | read one variable while other connections on the same server read another — so
    | overriding only the first leaves part of the app still talking to the shared
    | database, and the isolation silently does nothing. If a project has a second
    | connection (a `central` alongside a tenant one, a reporting replica, a queue
    | database), name its variable here too.
    |
    */
    'env' => ['DB_DATABASE'],

    /*
    |--------------------------------------------------------------------------
    | Provisioning SQL
    |--------------------------------------------------------------------------
    |
    | SQL files run INSIDE a freshly created database, before anything migrates.
    | Paths are relative to the project root unless absolute.
    |
    | This is for what a schema assumes already exists: Postgres extensions, roles,
    | a search_path. Without it the failure is quiet and misleading — the database is
    | created fine, and then the first migration needing `citext` or `vector` fails
    | with an error about the extension rather than about the missing setup step.
    |
    |   'init' => ['database/init/extensions.sql'],
    |
    */
    'init' => [],

];
